sonar.exclusions=**/test/**,**/test-output/**,**/*.test.js,*snyk_report.html,*snyk_report.css,README.md,**/jest.config.js,**/jest.setup.js,**/eslint.config.js
sonar.coverage.exclusions=index.js
sonar.javascript.lcov.reportPaths=test-output/lcov.info
