const {
  DA,
  IP,
  SPS,
  DF,
  FCCS,
  XG,
  TR,
  RDPECS,
  RDPELS,
  BK,
  INT,
  OPA,
  NELS,
  FCLS,
  RDTLS,
  NECS,
  RDTCP,
  P1,
  EA,
  RDTEXQ,
  EXNRDPE,
  SFI,
  SFI_PILOT,
  LUMP_SUMS,
  VET_VISITS,
  CS,
  BPS,
  ES,
  FC,
  IMPS,
  SFI23,
  DELINKED,
  SFI_EXPANDED,
  COHT_CAPITAL,
  COHT_REVENUE,
  FPTT,
  WMP
} = require('./pillars')

module.exports = {
  [DA]: 'NMAN_DA',
  [IP]: 'NMAN_IP',
  [SPS]: 'NMAN_SPS',
  [DF]: 'NMAN_DF',
  [FCCS]: 'NMAN_FC',
  [XG]: 'NMAN_XG',
  [TR]: 'NMAN_TR',
  [RDPECS]: 'NMAN_RDPE',
  [RDPELS]: 'NMAN_RDPE',
  [BK]: 'NMAN_BK',
  [INT]: 'NMAN_INT',
  [OPA]: 'NMAN_OPA',
  [NELS]: 'NMAN_NELS',
  [FCLS]: 'NMAN_FCLS',
  [RDTLS]: 'NMAN_RDT',
  [NECS]: 'NMAN_NE',
  [RDTCP]: 'NMAN_RDT',
  [P1]: 'NMAN_NE',
  [EA]: 'NMAN_EA',
  [RDTEXQ]: 'NMAN_RDT',
  [EXNRDPE]: 'NMAN_RDT',
  [SFI]: 'PMAN_SFI',
  [SFI_PILOT]: 'PMAN_SFIP',
  [LUMP_SUMS]: 'NMAN_DA',
  [VET_VISITS]: 'NMAN_DA',
  [CS]: 'PMAN_CS',
  [BPS]: 'NMAN_DA',
  [ES]: 'NMAN_DA',
  [FC]: 'NMAN_DA',
  [IMPS]: 'NMAN_DA',
  [SFI23]: 'PMAN_SFIA',
  [DELINKED]: 'PMAN_DP',
  [SFI_EXPANDED]: 'PMAN_ESFIO',
  [COHT_CAPITAL]: 'PMAN_COHTC',
  [COHT_REVENUE]: 'PMAN_COHTR',
  [FPTT]: 'PMAN_FPTT',
  [WMP]: 'PMAN_WMP'
}
