module.exports = {
  SFI: 'SFI-22',
  SFI_PILOT: 'SFI-P',
  LUMP_SUMS: 'Lump Sums',
  VET_VISITS: 'Vet Visits (AHWR)',
  CS: 'CS',
  BPS: 'BPS',
  MANUAL: 'Manual Payments (Injection)',
  ES: 'Genesis (ES)',
  FC: 'GLOS (FC)',
  IMPS: 'IMPS',
  SFI23: 'SFI-23',
  DELINKED: 'Delinked Payments',
  SFI_EXPANDED: 'SFI-EO',
  COHT_REVENUE: 'CS-HT (Revenue)',
  COHT_CAPITAL: 'CS-HT (Capital)',
  FPTT: 'FPTT',
  WMP: 'WMP',
  SFI26: 'SFI-26'
}
